internship/cities/urls.py
from django.urls import path

from . import views


app_name = 'cities'

urlpatterns = [
    path('', views.index, name='index'),
    path('country_list/', views.country_list, name='country_list'),
    path('city_list/<country>/', views.city_list, name='city_list'),
    path('city_detail/<int:pk>/', views.city_detail, name='city_detail'),
    path('add_country/', views.add_country, name='add_country'),
    path('edit_country/<int:country_id>', views.edit_country, name='edit_country'),
    path('delete_country/<int:country_id>', views.delete_country, name='delete_country'),
    path('add_city/<country>', views.add_city, name='add_city'),
    path('edit_city/<int:city_id>', views.edit_city, name='edit_city'),
    path('delete_city/<int:city_id>', views.delete_city, name='delete_city'),
]

internship/internship/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path

urlpatterns = [
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('cities.urls')),
    path('tests/', include('tests.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

internship/users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
]

internship/cities/models.py
from django.db import models
from pytils.translit import slugify


class Country(models.Model):
    name = models.CharField(max_length=255)
    country_code = models.CharField(max_length=3)
    population = models.IntegerField()
    flag = models.ImageField(
        'Flag',
        upload_to='flags/',
        blank=True
    )

    class Meta:
        verbose_name = 'Country'
        verbose_name_plural = 'Countries'

    def __str__(self):
        return self.name


class City(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    country = models.ForeignKey(
        Country,
        on_delete=models.CASCADE,
        related_name='cities'
    )
    population = models.IntegerField(blank=True, null=True)
    slug = models.SlugField(blank=True, null=True)
    emblem = models.ImageField(
        'Emblem',
        upload_to='emblems/',
        blank=True
    )
    with_mcdonalds = models.BooleanField()

    class Meta:
        verbose_name = 'City'
        verbose_name_plural = 'Cities'

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)[:50]
        super().save(*args, **kwargs)

internship/cities/forms.py
from django import forms

from .models import Country, City


class CountryForm(forms.ModelForm):

    class Meta:
        model = Country
        fields = ('name', 'country_code', 'population', 'flag')
        labels = {
            'name': ('Name:'),
            'country_code': ('Country code ISO 3166:'),
            'population': ('Population:'),
            'flag': ('Upload flag of country')
        }


class CityForm(forms.ModelForm):
    class Meta:
        model = City
        fields = ('name', 'description', 'population', 'emblem', 'with_mcdonalds')
        labels = {
            'name': ('Name:'),
            'description': ('Description:'),
            'population': ('Population:'),
            'emblem': ('Upload emblem of the city:'),
            'with_mcdonalds': ('Is McDonald\'s in this city?')
        }
        widgets = {
                    'description': forms.Textarea(attrs={"class": "form-control"}),
                    'with_mcdonalds': forms.CheckboxInput(attrs={
                        "class": "form-check-input",
                        "type": "checkbox"}
                    ),
                }

internship/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model


User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

internship/cities/views.py
from django.conf import settings
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import (
    render, get_object_or_404, get_list_or_404, redirect
)

from .models import Country, City
from .forms import CountryForm, CityForm


def index(request):
    return render(request, 'index.html')


def country_list(request):
    countries = get_list_or_404(Country)
    paginator = Paginator(countries, settings.PAGES_OBG_AMT)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    return render(request, 'country_list.html', {'page': page})


def city_list(request, country):
    country = get_object_or_404(Country, name=country)
    mcdonalds_value = request.GET.get('with_mcdonalds')
    if mcdonalds_value:
        cities = country.cities.filter(with_mcdonalds=mcdonalds_value)
    else:
        cities = country.cities.all()
    paginator = Paginator(cities, settings.PAGES_OBG_AMT)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    context = {'page': page, 'country': country}
    return render(request, 'city_list.html', context)


def city_detail(request, pk):
    city = get_object_or_404(City, pk=pk)
    return render(request, 'city_detail.html', {'city': city})


@login_required()
def add_country(request):
    header = 'Add Country'
    action = 'Add'
    form = CountryForm(request.POST or None, files=request.FILES or None)
    if form.is_valid():
        new_country = form.save(commit=False)
        new_country.save()
        return redirect('cities:country_list')
    return render(
        request,
        'new.html',
        {'form': form, 'header': header, 'action': action}
    )


@login_required()
def edit_country(request, country_id):
    header = 'Edit'
    action = 'Save'
    country = get_object_or_404(Country, pk=country_id)
    form = CountryForm(
        request.POST or None,
        files=request.FILES or None,
        instance=country
    )
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return redirect('cities:country_list')

    context = {
        'form': form, 'country': country, 'header': header, 'action': action,
        'country_id': country_id,
    }
    return render(request, 'new.html', context)


@staff_member_required()
def delete_country(request, country_id):
    country = get_object_or_404(Country, pk=country_id)
    country.delete()
    return redirect('cities:country_list')


@login_required()
def add_city(request, country):
    header = 'Add City'
    action = 'Add'
    country = get_object_or_404(Country, name=country)
    form = CityForm(request.POST or None, files=request.FILES or None)
    if form.is_valid():
        new_city = form.save(commit=False)
        new_city.country = country
        new_city.save()
        return redirect('cities:city_list', country=country.name)
    return render(
        request,
        'new.html',
        {'form': form, 'header': header, 'action': action}
    )


@login_required()
def edit_city(request, city_id):
    header = 'Edit'
    action = 'Save'
    city = get_object_or_404(City, pk=city_id)
    form = CityForm(
        request.POST or None,
        files=request.FILES or None,
        instance=city
    )
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return redirect('cities:city_list', country=city.country)

    context = {
        'form': form, 'city': city, 'header': header, 'action': action,
        'city_id': city_id,
    }
    return render(request, 'new.html', context)


@staff_member_required()
def delete_city(request, city_id):
    city = get_object_or_404(City, pk=city_id)
    city.delete()
    return redirect('cities:city_list', country=city.country)

internship/users/views.py
from django.views.generic import CreateView
from django.urls import reverse_lazy

from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('cities:index')
    template_name = 'users/signup.html'

internship/templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/datatables.css' %}">
    <link rel="stylesheet" href="{% static 'css/dataTables.bootstrap5.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery.dataTables.min.css' %}">
    <script type="text/javascript" charset="utf8" src="{% static 'js/jquery-3.6.0.js' %}"></script>
    <script type="text/javascript" charset="utf8" src="{% static 'js/jquery.dataTables.min.js' %}"></script>
    <script type="text/javascript" charset="utf8" src="{% static 'js/dataTables.bootstrap5.min.js' %}"></script>
    <title>{% block title %}Weather forecast service{% endblock %}</title>
</head>
<body>
    {% include "includes/nav.html" %}
    {% block content %}
    {% endblock %}
    {% include "includes/footer.html" %}
</body>
</html>

internship/templates/city_detail.html
{% extends "base.html" %}
<title>
  {% block title %}
    Information about {{ city.name }}
  {% endblock %}
</title>
{% block content %}
<body>
 <br>
    <div class="container">
        <p>{{ city.description }}</p>
    </div>
</body>
{% endblock %}

internship/templates/city_list.html
{% extends "base.html" %}
{% load user_filters %}
{% load thumbnail %}

<title>
  {% block title %}
    The list of cities
  {% endblock %}
</title>

{% block content %}
<body>
<div class="container-fluid mt-3">
	<div class="row">
    <!--menu -->
    <div class="col-lg-3 mx-auto">
        <div class="list-group">
            {% if user.is_authenticated %}
            <a class="list-group-item active" href="{% url 'cities:add_city' country %}">Add City</a>
            {% endif %}
            <a href="{% url 'cities:city_list' country %}" class="list-group-item list-group-item-action">All cities</a>
            <a href="{% url 'cities:city_list' country %}?with_mcdonalds=True" class="list-group-item list-group-item-action">Cities with McDonald's</a>
            <a href="{% url 'cities:city_list' country %}?with_mcdonalds=False" class="list-group-item list-group-item-action">Cities without McDonald's</a>
        </div>
    </div>
       <!--data-table -->
    <div class="col-lg-9 mx-auto">
    <div class="row mx-auto">
     {% if page %}
        <table class="table table-image display cell-border" id="city-table" >
           <thead>
             <tr>
               <th scope="col">№</th>
               <th scope="col">Emblem</th>
               <th scope="col">City</th>
               <th scope="col">Population</th>
               <th scope="col">With a McDonald's outlet</th>
               {% if user.is_authenticated %}
               <th scope="col">Edit city</th>
               {% endif %}
               {%  if user.is_staff %}
               <th scope="col">Delete city</th>
               {% endif %}
               </tr>
           </thead>
            <tbody >
             {% for city in page %}
              <tr>
                 <th scope="row"> {{ forloop.counter0|add:page.start_index }}</th>
                  <td class="w-10">{% thumbnail city.emblem "50x25" crop="center" upscale=True as im %}
                            <img class="img-fluid img-thumbnail" src="{{ im.url }}">
                        {% endthumbnail %}</td>
                   <td ><a class="nav-link" href="{% url 'cities:city_detail' city.pk %}">{{ city.name }}</a></td>
                  {% if city.population < 500000 %} <td style="color:#DC143C"> {{ city.population }} </td>
                  {% elif city.population < 1000000 %} <td style="color:#000080"> {{ city.population }} </td>
                  {% else %} <td style="color:#3CB371"> {{ city.population }} </td> {% endif %}
                  <td >{{ city.with_mcdonalds|add_image }}</td>
                  {% if user.is_authenticated %}
                  <td ><a class="btn btn-sm btn-primary" href="{% url 'cities:edit_city' city.id %}" role="button">Edit city</a></td>
                  {% endif %}
                  {% if user.is_staff %}
                  <td ><a class="btn btn-sm btn-danger" href="{% url 'cities:delete_city' city.id %}" role="button">Delete city</a></td>
                  {% endif %}
             </tr>
            {% endfor %}
            </tbody>
        </table>
    {% endif %}
    </div>
    </div></div></div>

{% include "includes/paginator.html" with items=page paginator=paginator %}

{% block js %}
    <script type="text/javascript">
        $(document).ready(function() {
            $('#city-table').DataTable({
                paging: false,
                searching: false,
                info: false,
                columnDefs: [
                    {
                        targets: "_all",
                        className: 'dt-center'
                    }
                ]
            } );
        });
    </script>
{% endblock js %}
</body>
{% endblock %}

internship/templates/country_list.html
{% extends "base.html" %}
{% load thumbnail %}
<title>
  {% block title %}
    The list of countries
  {% endblock %}
</title>

{% block content %}
<body>
 <br>
    <div class="container">
    {% if user.is_authenticated %}
    <div class="row">
        <div class="col-10">
            <a class="btn btn-sm btn-primary" href="{% url 'cities:add_country' %}" role="button">Add country</a>
        </div>
    </div>
    {% endif %}
    <div class="row">
        <div class="col-9">
     {% if page %}
        <table class="table table-image display cell-border" id="country-table">
           <thead>
             <tr>
               <th scope="col">№</th>
               <th scope="col">Flag</th>
               <th scope="col">Country</th>
               <th scope="col">Population</th>
               <th scope="col">Country code ISO 3166</th>
               {% if user.is_authenticated %}
               <th scope="col">Edit country</th>
               {% endif %}
               {%  if user.is_staff %}
               <th scope="col">Delete country</th>
               {% endif %}
             </tr>
           </thead>
            <tbody >
             {% for country in page %}
              <tr>
                 <th scope="row"> {{ forloop.counter0|add:page.start_index }}</th>
                  <td class="w-10">{% thumbnail country.flag "50x25" crop="center" upscale=True as im %}
                            <img class="img-fluid img-thumbnail" src="{{ im.url }}">
                        {% endthumbnail %}</td>
                  <td ><a class="nav-link" href="{% url 'cities:city_list' country.name %}">{{ country|upper }}</a></td>
                  <td >{{ country.population }}</td>
                  <td >{{ country.country_code }}</td>
                  {% if user.is_authenticated %}
                  <td><a class="btn btn-sm btn-primary" href="{% url 'cities:edit_country' country.id %}" role="button">Edit country</a></td>
                  {% endif %}
                  {%  if user.is_staff %}
                  <td><a class="btn btn-sm btn-danger" href="{% url 'cities:delete_country' country.id %}" role="button">Delete country</a></td>
                  {% endif %}
              </tr>
            {% endfor %}
            </tbody>
        </table>
    {% endif %}
    </div></div></div>

{% include "includes/paginator.html" with items=page paginator=paginator %}

{% block js %}
    <script type="text/javascript">
         $(document).ready(function() {
            $('#country-table').DataTable({
                paging: false,
                searching: false,
                info: false,
                columnDefs: [
                    {
                        targets: "_all",
                        className: 'dt-center'
                    }
                ]
            } );
        });
    </script>
{% endblock js %}
</body>
{% endblock %}

internship/templates/includes/footer.html
<div class="fixed-bottom">
  <footer class="footer mt-auto">
    <ul class="nav justify-content-center border-bottom pb-3 mb-3">
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Features</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Pricing</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">FAQs</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">About</a></li>
    </ul>
    <p class="text-center text-muted">© {% now 'Y' %} WFS, Inc</p>
  </footer>
</div>

internship/templates/includes/nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'cities:index' %}">Weather forecast service</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'cities:index' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'cities:country_list' %}">Countries</a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'users:logout' %}">Logout</a>
        </li>
        {% else %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'users:login' %}">Login</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'users:signup' %}">SignUp</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>

internship/templates/includes/paginator.html
{% load user_filters %}
{% if page.has_other_pages %}
<nav>
  <ul class="pagination justify-content-center">
    {% if page.has_previous %}
    <li class="page-item">
      <a class="page-link" href="{% relative_url page.previous_page_number 'page' request.GET.urlencode %}">&laquo; Previous</a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <span class="page-link">&laquo; Previous</span>
    </li>
    {% endif %}
    {% for i in page.paginator.page_range %}
    {% if page.number == i %}
    <li class="page-item active">
      <span class="page-link">{{ i }}</span>
    </li>
    {% else %}
    <li class="page-item">
      <a class="page-link" href="{% relative_url i 'page' request.GET.urlencode %}">{{ i }}</a>
    </li>
    {% endif %}
    {% endfor %}
    {% if page.has_next %}
    <li class="page-item">
      <a class="page-link" href="{% relative_url page.next_page_number 'page' request.GET.urlencode %}">Next &raquo;</a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <span class="page-link">Next &raquo;</span>
    </li>
    {% endif %}
  </ul>
</nav>
{% endif %}

internship/templates/index.html
{% extends "base.html" %}
{% block content %}
    <main>
        <div class="container">
            <h1>{% block header %}The Last Weather forecast service You'll Ever Need{% endblock %}</h1>
        </div>
    </main>
{% endblock %}

internship/templates/new.html
{% extends "base.html" %}
{% block content %}
{% load user_filters %}
{% load static %}
<div class="row justify-content-center">
    <div class="col-md-8 p-5">
        <div class="card">
            <div class="card-header">New notification</div>
            <div class="card-body">

                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.media }}
                    {% for field in form %}
                        <div class="form-group row" aria-required={% if field.field.required %}"true"{% else %}"false"{% endif %}>
                                    <label for="{{ field.id_for_label }}" class="col-md-4 col-form-label text-md-right">{{ field.label }}{% if field.field.required %}<span class="required">*</span>{% endif %}</label>
                                    <div class="col-md-6">
                                        {{ field }}
                                        {% if field.help_text %}
                                        <small id="{{ field.id_for_label }}-help" class="form-text text-muted">{{ field.help_text|safe }}</small>
                                        {% endif %}
                                    </div>
                        </div>
                    {% endfor %}

                    <div class="col-md-6 offset-md-4">
                            <button type="submit" class="btn btn-primary">
                                {{ action }}
                            </button>
                    </div>
                </form>

            </div> <!-- card body -->
        </div> <!-- card -->
    </div> <!-- col -->
</div> <!-- row -->
{% endblock %}

internship/templates/new_country.html
{% extends "base.html" %}
{% block content %}
{% load user_filters %}
{% load static %}
<div class="row justify-content-center">
    <div class="col-md-8 p-5">
        <div class="card">
            <div class="card-header">New notification</div>
            <div class="card-body">

                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.media }}
                    {% for field in form %}
                        <div class="form-group row" aria-required={% if field.field.required %}"true"{% else %}"false"{% endif %}>
                                    <label for="{{ field.id_for_label }}" class="col-md-4 col-form-label text-md-right">{{ field.label }}{% if field.field.required %}<span class="required">*</span>{% endif %}</label>
                                    <div class="col-md-6">
                                        {{ field|addclass:"form-control" }}
                                        {% if field.help_text %}
                                        <small id="{{ field.id_for_label }}-help" class="form-text text-muted">{{ field.help_text|safe }}</small>
                                        {% endif %}
                                    </div>
                        </div>
                    {% endfor %}

                    <div class="col-md-6 offset-md-4">
                            <button type="submit" class="btn btn-primary">
                                {{ action }}
                            </button>
                    </div>
                </form>

            </div> <!-- card body -->
        </div> <!-- card -->
    </div> <!-- col -->
</div> <!-- row -->
{% endblock %}

internship/templates/users/logged_out.html
{% extends 'base.html' %}
{% block title %}You logged out{% endblock %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        Logg out
      </div>
      <div class="card-body">
        <p>
          You logged out. See you later!
        </p>
      </div> <!-- card body -->
    </div> <!-- card -->
  </div> <!-- col -->
</div> <!-- row -->
{% endblock %} 

internship/templates/users/login.html
{% extends "base.html" %}
{% block title %}Войти{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Войти на сайт
        </div>
        <div class="card-body">
          {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}            
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
          {% endif %}

          <form method="post"
            {% if action_url %}
              action="{% url action_url %}"
            {% endif %}
          >
          {% csrf_token %}

          {% for field in form %}
            <div class="form-group row my-3"
              {% if field.field.required %} 
                aria-required="true"
              {% else %}
                aria-required="false"
              {% endif %}
            >
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
              </label>
              <div>
              {{ field }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
            </div>
          {% endfor %}
          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
              Войти
            </button>
             <a href="{% url 'password_reset' %}" class="btn btn-link">
              Забыли пароль?
            </a>
          </div>
          </form>
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
</div> <!-- row -->
{% endblock %} 

internship/templates/users/signup.html
{% extends "base.html" %}
{% block title %}Register{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Register
        </div>
        <div class="card-body">
          {% if form.errors %}
            {% for field in form %}
              {% for error in field.errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
              <div class="alert alert-danger">
                {{ error|escape }}
              </div>
            {% endfor %}
          {% endif %}

            <form method="post" action="{% url 'users:signup' %}">
              {% csrf_token %}
              {% for field in form %}
              <div class="form-group row my-3 p-3">
                <label for="{{ field.id_for_label }}">
                  {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
                </label>
                {{ field }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
              {% endfor %}
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  Register
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
  </div>
{% endblock %} 